import 'mocha';
import { expect } from "chai";
import {MazeBuilder} from "../../MazeBuilder";
import {Maze} from "../../Maze";
import {CardinalityBehaviorEight2D} from "../../Behavior/CardinalityBehaviorEight2D";
import {CardinalityBehaviorFour2D} from "../../Behavior/CardinalityBehaviorFour2D";

describe( 'MazeBuilder', () => {

    let MB: MazeBuilder;

    it( 'generates randomized mazes composed of randomly interconnected graph nodes', () => {

        MB = new MazeBuilder();

        let a: Maze = MB.buildMaze();
        let b: Maze = MB.buildMaze();
        let c: Maze = MB.buildMaze();

        expect( a.getSize() ).not.to.be.equal( b.getSize() );
        expect( a.getSize() ).not.to.be.equal( c.getSize() );
        expect( b.getSize() ).not.to.be.equal( c.getSize() );
    });

    it( 'can enforce cardinality behaviors to all MazeNodes by applying an instance of CardinalityBehavior', () => {

        MB = new MazeBuilder( new CardinalityBehaviorEight2D() );
        let a: Maze = MB.buildMaze();
        expect( a.getStartNode().getCardinality() ).to.be.an.instanceOf( CardinalityBehaviorEight2D );

        MB = new MazeBuilder( new CardinalityBehaviorFour2D() );
        let b: Maze = MB.buildMaze();
        expect( b.getStartNode().getCardinality() ).to.be.an.instanceOf( CardinalityBehaviorFour2D );
    });

    it( 'facilitates integer randomization as a static convenience service', () => { //@TODO Known Bug - fix!

        let min = 0;
        let max = 3;

        let numbersFound = [ false, false, false, false ];

        for ( let i = 0 ; i < 1000 ; i++ ) {

            expect( () => { numbersFound[ MazeBuilder.rand( max, min) ] = true; } ).not.to.throw();
        }

        for ( let i = 0 ; i <= max ; i++ ) {

            expect( numbersFound[i] ).to.be.true;
        }
    });

    it( 'will provide a coordinate collection of nodes generated by the build algorithm', () => {

        MB = new MazeBuilder();
        let maze = MB.buildMaze();

        expect( Object.keys( MB.getCoordinatesCollection() ) ).to.have.length.greaterThan( 0 );
    });

    // Tricky/expensive to prove without a search algorithm.  Will implement this on the official.  Mean while, these tests are pending.
    it( 'can generate a random path from a given node' );
    it( 'can generate a random path from a random existing node (sourced from provided node)' );
    // Has consistency issues.  Foregoing testing until solved.
    it( 'has a configurable complexity which determines the size, difficulty of maze' );

});